//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceConeInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONEINFOContext : DbContext
    {
        public CONEINFOContext()
            : base("name=CONEINFOContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AnalyticsMetric> AnalyticsMetrics { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Keyword> Keywords { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Search> Searches { get; set; }
        public DbSet<SearchLog> SearchLogs { get; set; }
    }
}
