//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceConeInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int number { get; set; }
        public string officeNumber { get; set; }
        public string departmentName { get; set; }
        public int personNumber { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
