//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceConeInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.Searches = new HashSet<Search>();
            this.SearchLogs = new HashSet<SearchLog>();
        }
    
        public int type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Search> Searches { get; set; }
        public virtual ICollection<SearchLog> SearchLogs { get; set; }
    }
}
