//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceConeInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public Search()
        {
            this.SearchLogs = new HashSet<SearchLog>();
        }
    
        public int id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public string url { get; set; }
        public int top10 { get; set; }
        public Nullable<int> keywordType { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual ICollection<SearchLog> SearchLogs { get; set; }
    }
}
