//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConeInfoManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string logonId { get; set; }
        public string passwd { get; set; }
        public string logonName { get; set; }
        public string logonHours { get; set; }
        public string logoffHours { get; set; }
        public bool logonStatus { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string roles { get; set; }
        public int personNumber { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
