//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConeInfoManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.People = new HashSet<Person>();
            this.Provinces = new HashSet<Province>();
        }
    
        public string code { get; set; }
        public string alpha2Code { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
